Rapsys\AirBundle\Entity\Application:
    type: entity
    repositoryClass: Rapsys\AirBundle\Repository\ApplicationRepository
    table: applications
    id:
        id:
            type: integer
            generator: 
                strategy: AUTO
            options:
                unsigned: true
    fields:
#The score computed at attribution time, the sum of all session score divided by proximity in days (1 for sun-thu, 2 for fri-sat, +1 for high temperature, *-1 for bad weather)/abs(DAY(attribution date - session.date))
#        score:
#            type: float
        created:
            type: datetime
        updated:
            type: datetime
    manyToOne:
        session:
            targetEntity: Rapsys\AirBundle\Entity\Session
            inversedBy: applications
        user:
            targetEntity: Rapsys\AirBundle\Entity\User
            inversedBy: applications
    oneToMany:
        votes:
            targetEntity: Rapsys\AirBundle\Entity\Vote
            mappedBy: application
