Rapsys\AirBundle\Entity\Civility:
    type: entity
    #repositoryClass: Rapsys\AirBundle\Repository\CivilityRepository
    table: civilities
    oneToMany:
        users:
            targetEntity: User
            mappedBy: civility
