Rapsys\AirBundle\Entity\Dance:
    type: entity
    repositoryClass: Rapsys\AirBundle\Repository\DanceRepository
    table: dances
    id:
        id:
            type: integer
            generator: 
                strategy: AUTO
            options:
                unsigned: true
    fields:
        title:
            type: string
            length: 32
        created:
            type: datetime
        updated:
            type: datetime
    oneToMany:
        applications:
            targetEntity: Rapsys\AirBundle\Entity\Application
            mappedBy: dance
    manyToMany:
        users:
            targetEntity: Rapsys\AirBundle\Entity\User
            mappedBy: dances
    lifecycleCallbacks:
        preUpdate: ['preUpdate']
