Rapsys\AirBundle\Entity\GoogleCalendar:
    type: entity
    #repositoryClass: Rapsys\AirBundle\Repository\GoogleCalendarRepository
    table: google_calendars
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
            options:
                unsigned: true
    fields:
        mail:
            type: string
            length: 1024
        summary:
            type: string
            length: 255
#        description:
#            type: string
#            length: 200
#        location:
#            type: string
#            length: 1024
#        timezone:
#            type: string
#            length: 32
        synchronized:
            type: datetime
        created:
            type: datetime
        updated:
            type: datetime
    manyToOne:
        googleToken:
            targetEntity: Rapsys\AirBundle\Entity\GoogleToken
            inversedBy: googleCalendars
            joinColumn:
                nullable: false
#    uniqueConstraints:
#        user_mail:
#            columns: [ user_id, mail ]
    lifecycleCallbacks:
        preUpdate: ['preUpdate']
