Rapsys\AirBundle\Entity\Slot:
    type: entity
    repositoryClass: Rapsys\AirBundle\Repository\SlotRepository
    table: slots
    id:
        id:
            type: integer
            generator: 
                strategy: AUTO
            options:
                unsigned: true
    fields:
        title:
            type: string
            length: 16
        created:
            type: datetime
        updated:
            type: datetime
    oneToMany:
        sessions:
            targetEntity: Rapsys\AirBundle\Entity\Session
            mappedBy: slot
    lifecycleCallbacks:
        preUpdate: ['preUpdate']
