Rapsys\AirBundle\Entity\Vote:
    type: entity
    #repositoryClass: Rapsys\AirBundle\Repository\VoteRepository
    table: votes
    id:
        id:
            type: integer
            generator: 
                strategy: AUTO
            options:
                unsigned: true
    fields:
        created:
            type: datetime
        updated:
            type: datetime
    manyToOne:
        application:
            targetEntity: Rapsys\AirBundle\Entity\Application
            inversedBy: votes
        user:
            targetEntity: Rapsys\AirBundle\Entity\User
            inversedBy: votes
