#https://symfony.com/doc/current/routing.html#localized-routes-i18n
#SCRUD: index, add, edit, delete, view
rapsys_air:
    path:
        en: '/en'
        fr: '/'
    controller: Rapsys\AirBundle\Controller\DefaultController::index
    methods: GET

rapsys_air_contact:
    path:
        en: '/en/contact'
        fr: '/contact'
    controller: Rapsys\AirBundle\Controller\DefaultController::contact
    methods: GET|POST

rapsys_air_regulation:
    path:
        en: '/en/regulation'
        fr: '/reglement'
    controller: Rapsys\AirBundle\Controller\DefaultController::regulation
    methods: GET

rapsys_air_location_view:
    path:
        en: '/en/location/{id<\d+>}'
        fr: '/emplacement/{id<\d+>}'
    controller: Rapsys\AirBundle\Controller\LocationController::view
    methods: GET

rapsys_air_application_add:
    path:
        en: '/en/application'
        fr: '/reservation'
    controller: Rapsys\AirBundle\Controller\ApplicationController::add
    methods: POST

rapsys_air_session:
    path:
        en: '/en/session'
        fr: '/seance'
    controller: Rapsys\AirBundle\Controller\SessionController::index
    methods: GET

rapsys_air_session_edit:
    path:
        en: '/en/session/{id<\d+>}'
        fr: '/seance/{id<\d+>}'
    controller: Rapsys\AirBundle\Controller\SessionController::edit
    methods: POST

rapsys_air_session_view:
    path:
        en: '/en/session/{id<\d+>}'
        fr: '/seance/{id<\d+>}'
    controller: Rapsys\AirBundle\Controller\SessionController::view
    methods: GET

rapsys_air_user:
    path:
        en: '/en/user'
        fr: '/utilisateur'
    controller: Rapsys\AirBundle\Controller\UserController::index
    methods: GET

rapsys_air_user_view:
    path:
        en: '/en/user/{id<\d+>}'
        fr: '/utilisateur/{id<\d+>}'
    controller: Rapsys\AirBundle\Controller\UserController::view
    methods: GET
